<?php

return [
    [
        "title"=> 'progetto 1',
        "slug"=> 'null-1',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=>date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 2',
        "slug"=> 'null-2',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 3',
        "slug"=> 'null-3',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 4',
        "slug"=> 'null-4',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 5',
        "slug"=> 'null-5',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 6',
        "slug"=> 'null-6',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 7',
        "slug"=> 'null-7',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 8',
        "slug"=> 'null-8',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 9',
        "slug"=> 'null-9',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],
    [
        "title"=> 'progetto 10',
        "slug"=> 'null-10',
        "type"=> 'Front end',
        "thumb"=> 'image',
        "date_creation"=> date_create_from_format('d/m/Y', '02/06/2023')->format('Y-m-d'),
        "description"=> 'descrizione progetto',
    ],

    ];
